apiVersion: batch/v1
kind: Job
metadata:
  name: zeebe-export-pause
spec:
  template:
    spec:
      containers:
      - name: pause-exporting
        image: curlimages/curl
        command: ["/bin/sh"]
        args:
        - -c
        - |
          #!/bin/bash
          curl --fail -X POST "http://camunda-zeebe-gateway:9600/actuator/exporting/pause?soft=true" \
            -H 'Content-Type: application/json' \
            -d '{}'
          success=$?
          if [ "$success" ]; then
            echo "Exporting paused on camunda-zeebe-gateway."
          else
            echo "ERROR: Could not pause exporting on camunda-zeebe-gateway"  >&2
            exit 1
          fi
      restartPolicy: Never