global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false

# Disable identity as part of the camunda platform core
identity:
  enabled: false

optimize:
  enabled: false

# Reduce for Zeebe and Gateway the configured replicas and with that the required resources
# to get it running locally
zeebe:
  affinity:
    podAntiAffinity: null
  clusterSize: 3
  partitionCount: 3
  replicationFactor: 3
  pvcSize: 10Gi
  resources:
    requests:
      cpu: "100m"
      memory: "1Gi"
    limits:
      cpu: "512m"
      memory: "3Gi"
  env:
  - name: ZEEBE_BROKER_DATA_BACKUP_STORE
    value: "S3"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
    value: "c8-backup"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS
    value: "true"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
    value: "http://minio.default.svc.cluster.local:9000"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
    value: "7KO3AkzJEe22e85dy6wL"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
    value: "AcK06TIRw8ZSLp1mzyY5ANV15xZmgqqyIg1IMoqq"
  - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
    value: "us-east-1"
  initContainers:
  - name: zeebe-restore
    image: camunda/zeebe
    command: ["/bin/bash"]
    args: [ "-c" ,"export ZEEBE_BROKER_CLUSTER_NODEID=${ZEEBE_BROKER_CLUSTER_NODEID:-${K8S_NAME##*-}};
                        env;
                        echo ClusterId is $ZEEBE_BROKER_CLUSTER_NODEID;
                        if [ ${ZEEBE_RESTORE} = true ];
                        then
                          ls -laR /usr/local/zeebe/data;
                          rm -rf /usr/local/zeebe/data/lost+found;
                          exec /usr/local/zeebe/bin/restore --backupId=${ZEEBE_RESTORE_FROM_BACKUP_ID};
                        fi"]
    volumeMounts:
    - name: data
      mountPath: /usr/local/zeebe/data
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
    env:
    - name: K8S_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: ZEEBE_BROKER_CLUSTER_PARTITIONSCOUNT
      value: "3"
    - name: ZEEBE_BROKER_CLUSTER_CLUSTERSIZE
      value: "3"
    - name: ZEEBE_BROKER_CLUSTER_REPLICATIONFACTOR
      value: "3"
    - name: ZEEBE_BROKER_DATA_BACKUP_STORE
      value: "S3"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_BUCKETNAME
      value: "c8-backup"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_FORCEPATHSTYLEACCESS
      value: "true"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_ENDPOINT
      value: "http://minio.default.svc.cluster.local:9000"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_ACCESSKEY
      value: "7KO3AkzJEe22e85dy6wL"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_SECRETKEY
      value: "AcK06TIRw8ZSLp1mzyY5ANV15xZmgqqyIg1IMoqq"
    - name: ZEEBE_BROKER_DATA_BACKUP_S3_REGION
      value: "us-east-1"
    - name: ZEEBE_RESTORE_FROM_BACKUP_ID
      value: "1"
    - name: ZEEBE_RESTORE
      value: "true"


zeebe-gateway:
  replicas: 1

connectors:
  enabled: true
  inbound:
    mode: disabled

# Configure elastic search to make it running for local development
elasticsearch:
  master:
    replicaCount: 1
    # Request smaller persistent volumes.
    persistence:
      size: 15Gi

