global:
  identity:
    auth:
      # Disable the Identity authentication for local development
      # it will fall back to basic-auth: demo/demo as default user
      enabled: false
  image:
    tag: 8.2.20

operate:
  enabled: true

tasklist:
  enabled: true

optimize:
  enabled: false

connectors:
  enabled: false

identity:
  enabled: false

zeebe-gateway:
  replicas: 1

zeebe:
  clusterSize: 1
  partitionCount: 1
  replicationFactor: 1
  pvcSize: 10Gi

elasticsearch:
  imageTag: 7.17.15
  replicas: 2
  # Request smaller persistent volumes.
  persistence:
    size: 15Gi
